### PR TITLE
Debian/sid

### PR DESCRIPTION
**Pull request by gcsideal**
Some cleanup, make rebuildable. Target experimental as ProtoBuf 3 will exist there, version build dependency. Add packages for C++ bindings. Install examples with the C++ -dev package.

### CODE REVIEW

**Comment by andrewpollock** [comment]
Thanks for this. The only thing that I'd like to do differently is have a separate branch for experimental. We can get just the C bindings into unstable today, because there's no actual dependency on protobuf 3 for them.

**Comment by gcsideal** [comment]
Can you cherry pick the relevant changes or should I create new pull requests for Sid + Experimental?

**Comment by andrewpollock** [comment]
I can attempt to cherry pick. I'm very new to Github.

**Comment by andrewpollock** [comment]
> Can you cherry pick the relevant changes or should I create new pull requests for Sid + Experimental?

Okay I have successfully cherry-picked everything that is fit to go into unstable. I'll shortly create another branch for debian/experimental and cherry-pick the other bits and pieces into there.

**Comment by andrewpollock** [comment]
Okay I believe I have cherry picked everything from this PR into either debian/sid or debian/experimental. Could you please check for yourself and then close out this PR? (I assume that's the right thing to do at this point?)

**Pull request closed without merging**
